apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster 
subsets:
  - addresses:
      - ip: 172.16.1.245
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 172.16.1.246
    ports:
      - port: 1 
        protocol: TCP
